version: "2"

services:
  notification:
    build: ./
    environment:
      - OUT_AMQP_CONNECTIONSTRING=10.127.84.237:5672
      - IN_AMQP_CONNECTIONSTRING=10.127.84.237:5672
      - OUT_EXCHANGE=out
      - IN_EXCHANGE=in
      - IN_BINDINGKEY=
      - CONSUMERTAG_OVERRIDE=
    depends_on:
      - rabbit
    links:
      - rabbit
    
  rabbit:
    image: rabbitmq:3-management
    expose:
      - "5672"
    ports:
      - "5672:5672"
      - "15672:15672"