# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: stevenry
  tag: latest
  pullPolicy: Always
  repoCredsSecretName:


inAmqp:
  connectionString: amqp://<>-rabbit
  exchangeName: in
  bindingKey: reservation
  consumerTagOverride: 
outAmqp:
  connectionString: amqp://<>-rabbit
  exchangeName: out
